export const CATEGORY = {
    ELECTRICITY: "ELECTRICITY",
    WATER: "WATER",
    ROAD: "ROAD",
    SANITATION: "SANITATION",
    OTHER: "OTHER"
}

export const STATUS = {
    PENDING: "PENDING",
    ASSIGNED: "ASSIGNED",
    IN_PROGRESS: "IN_PROGRESS",
    RESOLVED: "RESOLVED",
    REJECTED: "REJECTED"
}

export const ROLES = {
    ADMIN: "ADMIN",
    SUPER_ADMIN: "SUPER_ADMIN",
    USER: "USER",
    DEPARTMENT_OFFICER: "DEPARTMENT_OFFICER"
}